examen_parcial/examen_parcial/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestion_tareas/', include('gestion_tareas.urls'))
]

examen_parcial/gestion_tareas/urls.py
from . import views
from django.urls import path

app_name = 'gestion_tareas'

urlpatterns = [
    path('',views.ingreso,name='ingreso'),
    path('dashboard',views.dashboard,name='dashboard'),
    path('eliminarTarea/<str:id>',views.eliminarTarea,name='eliminarTarea'),
    path('crearTarea',views.crearTarea,name='crearTarea'),
    path('detalleTarea/<str:id>',views.detalleTarea,name='detalleTarea'),
    path('editarTarea/<str:id>',views.editarTarea,name='editarTarea'),
    path('finalizarTarea/<str:id>',views.finalizarTarea,name='finalizarTarea')
]

examen_parcial/gestion_tareas/models.py
from django.db import models

# Create your models here.

class usuario(models.Model):
    nombre = models.CharField(max_length=128,default='')
    apellido = models.CharField(max_length=128,default='')
    codigo_usuario = models.CharField(max_length=128,default='')
    password_usuario = models.CharField(max_length=128,default='')

class tarea(models.Model):
    descripcion = models.CharField(max_length=128,default='')
    fecha_creacion = models.DateField(null=True)
    fecha_entrega = models.DateField(null=True)
    responsable = models.CharField(max_length=128,default='')#nombre de usuario responsable
    estado = models.CharField(max_length=40,default='')

examen_parcial/gestion_tareas/views.py
import datetime
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from gestion_tareas.models import tarea, usuario
from datetime import date, datetime
from dateutil.parser import parse
# Create your views here.

def ingreso(request):
    if request.method == 'POST':
        nombre = request.POST.get('nombre')
        password = request.POST.get('password')
        #validar usuario y contraseña
        user_registrado = 0
        user_totales = usuario.objects.all()
        for user in user_totales:
            if user.nombre == nombre and user.password_usuario == password:
                user_registrado = 1
        
        if user_registrado == 1:
            return HttpResponseRedirect(reverse('gestion_tareas:dashboard'))
        else:
            return render(request,'gestion_tareas/ingreso.html',{
                'mensaje':'USUARIO NO REGISTRADO'
            })
        #fin validar

    return render(request,'gestion_tareas/ingreso.html')

def dashboard(request):
    total_tareas = tarea.objects.all()

    return render(request,'gestion_tareas/dashboard.html',{
        'total_tareas':total_tareas
    })

def crearTarea(request):
    if request.method == 'POST':
        nombreTarea = request.POST.get('nombreTarea')
        fechaCreacion = request.POST.get('fechaCreacion')
        #print(type(fechaCreacion))
        fechaEntrega = request.POST.get('fechaEntrega')
        #print(type(fechaEntrega))
        #print(type(fechaEntrega), type(date.today()))
        #print(fechaEntrega, date.today())
        fechaEntrega = datetime.strptime(fechaEntrega, '%Y-%m-%d').date()
        #print(type(fechaEntrega))
        #print(type(fechaEntrega), type(date.today()))        
        responsableTarea = request.POST.get('responsableTarea')

        delta = fechaEntrega - date.today()
        #print("days delta vale: ",delta.days)
        #print("LA FECHA DE ENTREGA ES: ", fechaEntrega.day)
        if delta.days >= 3:
            estadoTarea = 'PROGRESO'
        elif  delta.days >= 0 and delta.days <= 3:
            estadoTarea = 'FINALIZANDO'
        elif delta.days < 0:
            estadoTarea = 'PENDIENTE'
        else:
            estadoTarea = 'FALLIDO'

        tarea(descripcion=nombreTarea,fecha_creacion=fechaCreacion,fecha_entrega=fechaEntrega,responsable=responsableTarea,estado=estadoTarea).save()

        return HttpResponseRedirect(reverse('gestion_tareas:dashboard'))

    return render(request,'gestion_tareas/crear_tarea.html')

def detalleTarea(request,id):
    tarea_detalle = tarea.objects.filter(id=id)
    return render(request,'gestion_tareas/detalleTarea.html',{
        'tarea_detalle':tarea_detalle
    })
# filter() will always give you a QuerySet" - it's iterable
# get() return single object and it's not iterable
# Basically use get() when you want to get a single unique object, 
# and filter() when you want to get all objects that match your lookup parameters.
def editarTarea(request,id):
    tarea_a_editar = tarea.objects.get(id=id)

    if request.method == 'POST':
        nombreTarea = request.POST.get('nombreTarea')
        fechaCreacion = request.POST.get('fechaCreacion')
        fechaEntrega = request.POST.get('fechaEntrega')
        fechaEntrega = datetime.strptime(fechaEntrega, '%Y-%m-%d').date()
        delta = fechaEntrega - date.today()
        if delta.days >= 3:
            estadoTarea = 'PROGRESO'
        elif  delta.days >= 0 and delta.days <= 3:
            estadoTarea = 'FINALIZANDO'
        elif delta.days < 0:
            estadoTarea = 'PENDIENTE'
        else:
            estadoTarea = 'FALLIDO'

        responsableTarea = request.POST.get('responsableTarea')
        tarea_a_editar.descripcion = nombreTarea
        tarea_a_editar.fecha_creacion = fechaCreacion
        tarea_a_editar.fecha_entrega = fechaEntrega
        tarea_a_editar.responsable = responsableTarea
        tarea_a_editar.estado = estadoTarea
        tarea_a_editar.save()

        
        return HttpResponseRedirect(reverse('gestion_tareas:dashboard'))


    return render(request,'gestion_tareas/editarTarea.html',{
        'tarea_a_editar': tarea_a_editar
    })

def eliminarTarea(request,id):

    tarea.objects.filter(id=id).delete()
    return HttpResponseRedirect(reverse('gestion_tareas:dashboard'))

def finalizarTarea(request,id):
    tarea_a_editar = tarea.objects.get(id=id)
    tarea_a_editar.estado = 'FINALIZADO'
    tarea_a_editar.save()
    return HttpResponseRedirect(reverse('gestion_tareas:dashboard'))

examen_parcial/gestion_tareas/templates/gestion_tareas/crear_tarea.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Crear tarea</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,500" rel="stylesheet" type="text/css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-xl-8 offset-xl-2">
                <h1>Crear tarea
                </h1>
                <form id="contact-form" method="post" action="{% url 'gestion_tareas:crearTarea' %}" role="form" novalidate="true">
                    {% csrf_token %}
                    <div class="controls">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="form_name">Tarea</label>
                                    <input id="form_name" type="text" class="form-control" name="nombreTarea">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="form_email">Fecha de creación</label>
                                    <input type="date" class="form-control" name="fechaCreacion">
                                    
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="form_phone">Fecha de entrega</label>
                                    <input type="date" class="form-control" name="fechaEntrega">
                                    
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="form_email">Responsable</label>
                                    <input id="form_email" type="text"  class="form-control" name="responsableTarea">
                                </div>
                            </div>
                        </div>
                        <a class="btn btn-success" href="{% url 'gestion_tareas:dashboard' %}">Regresar</a>
                        <div class="float-end">
                            <button type="submit" class="btn btn-success">Crear tarea</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

examen_parcial/gestion_tareas/templates/gestion_tareas/dashboard.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
        <title>dashboard</title>
    </head>
    <body>
        <div class="container">
            <h1>Dashboard tarea</h1>
            <div class="float-start">
                <a href="{% url 'gestion_tareas:ingreso' %}" class="btn btn-success"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0v2z"/>
                    <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z"/>
                  </svg> Salir</a>
            </div>
            <div class="float-end">
                <a href="{% url 'gestion_tareas:crearTarea' %}" class="btn btn-success"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-card-text" viewBox="0 0 16 16">
                    <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
                    <path d="M3 5.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 8a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 8zm0 2.5a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5z"/>
                  </svg> Crear tarea</a>
            </div>
            <table class="table">
                <thead style="text-align: center;">
                    <th>ID</th>
                    <th>Tarea</th>
                    <th>Estado</th>
                    <th>Ver detalles</th>
                    <th>Editar</th>
                    <th>Borrar</th>
                </thead>
                <tbody style="text-align: center;">
                    {% for tarea in total_tareas %}
                    <tr>
                        <td>{{tarea.id}}</td>
                        <td>{{tarea.descripcion}}</td>
                        {% if tarea.estado == 'PROGRESO' %}
                        <td style="background-color: rgb(24, 209, 24); font-size: 30px; font-weight: bold;">{{tarea.estado}}</td>
                        {% endif %}
                        {% if tarea.estado == 'FINALIZANDO' %}
                        <td style="background-color: rgb(255, 255, 0); font-size: 30px; font-weight: bold;">{{tarea.estado}}</td>
                        {% endif %}
                        {% if tarea.estado == 'FINALIZADO' %}
                        <td style="background-color: rgb(113, 219, 255); font-size: 30px; font-weight: bold;">{{tarea.estado}}</td>
                        {% endif %}
                        {% if tarea.estado == 'PENDIENTE' %}
                        <td style="background-color: rgb(255, 55, 55); font-size: 30px; font-weight: bold;">{{tarea.estado}}</td>
                        {% endif %}
                        {% if tarea.estado == 'FALLIDO' %}
                        <td style="background-color: rgb(255, 0, 234); font-size: 30px; font-weight: bold;">{{tarea.estado}}</td>
                        {% endif %}
                        <td><a class="btn btn-info"  href="{% url 'gestion_tareas:detalleTarea' tarea.id %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16">
                            <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
                            <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
                          </svg> Ver detalles</a></td>
                        <td><a class="btn btn-warning"  href="{% url 'gestion_tareas:editarTarea' tarea.id %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                          </svg> Editar</a></td>
                        <td><a class="btn btn-danger"  href="{% url 'gestion_tareas:eliminarTarea' tarea.id %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                          </svg> Eliminar</a></td>
                        <td><a class="btn btn-info" style="background-color: rgb(55, 255, 235);" href="{% url 'gestion_tareas:finalizarTarea' tarea.id %}">
                            Finalizar tarea</a>
                          </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </body>
</html>

examen_parcial/gestion_tareas/templates/gestion_tareas/detalleTarea.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Crear tarea</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,500" rel="stylesheet" type="text/css">

</head>
<body>
    <div class="container">
        <h1>Detalles de tarea</h1>
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Descripción</th>
                <th scope="col">Responsable</th>
                <th scope="col">Estado</th>
                <th scope="col">Fecha de creación</th>
                <th scope="col">Fecha de entrega</th>
            </tr>
            </thead>
            <tbody>
                {% for tarea in tarea_detalle %}
                <tr>
                    <td>{{tarea.id}}</td>
                    <td>{{tarea.descripcion}}</td>
                    <td>{{tarea.responsable}}</td>
                    <td>{{tarea.estado}}</td>
                    <td>{{tarea.fecha_creacion}}</td>
                    <td>{{tarea.fecha_entrega}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a class="btn btn-success" href="{% url 'gestion_tareas:dashboard' %}">Regresar</a>
    </div>
</body>
</html>

examen_parcial/gestion_tareas/templates/gestion_tareas/editarTarea.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Editar tarea</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,500" rel="stylesheet" type="text/css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-xl-8 offset-xl-2">
                <h1>Editar tarea
                </h1>
                <form id="contact-form" method="post" action="{% url 'gestion_tareas:editarTarea' tarea_a_editar.id %}" role="form" novalidate="true">
                    {% csrf_token %}
                    <div class="controls">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="form_name">Tarea</label>
                                    <input id="form_name" type="text" class="form-control" value="{{tarea_a_editar.descripcion}}" name="nombreTarea">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="form_email">Fecha de creación</label>
                                    <input type="date" class="form-control" value="{{tarea_a_editar.fecha_creacion|date:'Y-m-d'}}" name="fechaCreacion">
                                    
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="form_phone">Fecha de entrega</label>
                                    <input type="date" class="form-control" value="{{tarea_a_editar.fecha_entrega|date:'Y-m-d'}}" name="fechaEntrega">
                                    
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="form_email">Responsable</label>
                                    <input id="form_email" type="text"  class="form-control" value="{{tarea_a_editar.responsable}}" name="responsableTarea">
                                </div>
                            </div>
                        </div>
                        </div>
                        <a class="btn btn-success" href="{% url 'gestion_tareas:dashboard' %}">Regresar</a>
                        <div class="float-end">
                            <button type="submit" class="btn btn-success">Editar tarea</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

examen_parcial/gestion_tareas/templates/gestion_tareas/ingreso.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Ingreso</title>
        {% load static %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
        <link href="{% static 'gestion_tareas/style.css' %}" rel="stylesheet">
        
    </head>
    <body>
        <div class="container d-flex justify-content-center">    
            <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-2 col-md-offset-3 col-sm-8 col-sm-offset-2">                    
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <div class="panel-title" style="text-align: center;">
                            <h4>Ingreso</h4>
                        </div>
                        <br>
                        <h6>Usuario: hugo</h6>
                        <h6>Contraseña: 123456</h6>
                    </div>     
                    <div style="padding-top:30px" class="panel-body">
                        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12">
                        </div>
                        <form class="form-horizontal" method="POST" action="{% url 'gestion_tareas:ingreso' %}">
                            {% csrf_token %}
                            <div style="margin-bottom: 25px" class="input-group">
                                <span class="input-group-addon"></span>
                                <input type="text" class="form-control" name="nombre" placeholder="usuario">                                        
                            </div>   
                            <div style="margin-bottom: 25px" class="input-group">
                                <span class="input-group-addon"></span>
                                <input type="password" class="form-control" name="password" placeholder="contraseña">
                            </div>
                            <div style="margin-top:10px" class="form-group">
                                <!-- Button -->
                                <div class="col-sm-12 controls" style="text-align: center;">
                                    <button type="submit" href="{% url 'gestion_tareas:ingreso' %}" class="btn btn-success">Ingreso</button>
                                </div>
                                <br>
                                {% if mensaje %}
                                <div style="text-align: center;">{{mensaje}}</div>
                                {% endif%}
                            </div>
                        </form>
                    </div>                     
                </div>  
            </div>
        </div>
    </body>
</html>